contact_links:
    - name: 📄 Documentation Issue
      url: https://github.com/hund-studio/support/discussions/new?category=q-a
      about: This issue tracker is not for documentation issues. Please file documentation issues here.
    - name: 🆘 Questions and Help
      url: https://github.com/hund-studio/support/discussions/new?category=q-a
      about: This issue tracker is not for support questions. Please refer to the React community's help and discussion forums.
